[General]
  snippetfile = "/home/bollmann/.config/pet/snippet.toml"
  editor = "emacs -nw"
  column = 40
  selectcmd = "fzf --preview='_pet_preview_string {}'"
  backend = "gist"
  sortby = ""

[Gist]
  file_name = "pet-snippet.toml"
  access_token = "<Generate token via https://github.com/settings/tokens and add it here>"
  gist_id = "5971af48744aaaf56da8fce7954172bb"
  public = false
  auto_sync = true
